### ISSUE TITLE
login1234.xaa.pl - wyłudzanie danych do fb

### ISSUE THREAD

**Issue by RikoDEV** [PolishFiltersTeam/KADhosts#19]
Adres: http://login1234.xaa.pl/

![image](https://user-images.githubusercontent.com/18230443/52079754-8ba9e480-2596-11e9-8a4c-4ea44b75c98c.png)

**Comment by azet12** [comment]
Dzięki za zgłoszenie. Wysłałem do hostingu i już zablokowali.
