### ISSUE TITLE
Strony prozdrowotne i z suplementami - dlaczego?

### ISSUE THREAD

**Issue by PatrickMis** [PolishFiltersTeam/KADhosts#21]
Jestem bardzo sceptyczny do tworzenia szczególnie tego typu wpisów, jednocześnie absolutnie nie mogę się zgodzić z blokadą stron,, które naprawdę funkcjonują, korzystam z nich od wielu lat; a także z produktów sprzedawanych na tych stronach, dzięki którym m.in. pozbyłem się wielu tzw. nieuleczalnych chorób lub, innymi słowy,  takich, które przez dzisiejszą medycynę są uznawane za nieuleczalne. Wiedza na tych stronach jest zweryfikowana; a to, że jest niepopularna - stanowi już całkiem odrębną kwestię: strona z taką wiedzą nie powinna być pochopnie zaliczana do oszustów czy przekrętów - chyba, że lista jest sponsorowana przez firmy i/lub jednostki, którym na blokadzie takich stron zależy, bądź autor z góry, bez dokładnej weryfikacji uznał je za potencjalnie szkodliwe (jestem w stanie zrozumieć według zasady "lepiej dmuchać na zimne"). Lista bowiem nie nosi tytułu "blokowanie alternatywnej wiedzy", "anty-medycyna-komplementarna" bądź równoważnego.

Oto kilka z nich - przynajmniej te, co do których jestem pewien: 
```
ukryteterapie.pl
bio-chemik24.pl
planetazdrowia.com
vaccgenocide.wordpress.com
www.odkrywamyzakryte.com
jerzyzieba.com
stopnop.com.pl
szczepienie.info
```

Liczę na rzetelne podejście do problemu, bądź przynajmniej adnotację na stronie głównej, że lista ta zawiera także strony, których autorowi nie chciało się dogłębnie zweryfikować (co jest dla mnie jak najbardziej zrozumiałe) lub, że zawiera także strony mówiące prawdę, jednakże sprzeczne z ogólnie przyjętą przez system narracją.

Na koniec nadmieniam, iż lista z założenia (tytuł/opis) ma blokować oszustwa i przekręty; nie ma tutaj zatem mowy o stronach, które są podejrzane. Jak tytuł listy mówi, znaleźć się tu powinny strony, które są przekrętami i jest to absolutnie jednoznaczne, nie ma co do tego żadnych wątpliwości ani głosów sprzeciwu.

Poza tym inicjatywę stanowczo popieram i jestem w stanie wspierać, jeśli takie niedorzeczne blokady nie będą miały miejsca.

---

> _Wymoderowane przez @krystian3w_

**Comment by krystian3w** [comment]
See: **https://github.com/PolishFiltersTeam/KAD/issues/649**

**Comment by krystian3w** [comment]
Dobra z wydaniem `Version: 2019.5.27.6` udało mi się to  wyłączyć.

Teraz zostaje co na to @azet12  i @hawkeye116477.

**Comment by hawkeye116477** [comment]
Jak dla mnie to te strony wyglądają nieco podejrzanie, tak samo jak autor tego wątku, który zarzuca, że lista jest sponsorowana.

**Comment by hawkeye116477** [comment]
`zawiera także strony mówiące prawdę, jednakże sprzeczne z ogólnie przyjętą przez system narracją`
Ta, szczególnie ten ruch antyszczepionkowy...

**Comment by krystian3w** [comment]
Może coś da dodanie pliku:

```
198.185.159.144 jerzyzieba.com
```

chociaż nie wiem jak do dać w hosts i kiedy mają sobie importować, chyba po KAD z restrykcyjną blokadą i nie zawsze IPv4 zadziała lub może ktoś ma stronę IPv6...

**Comment by krystian3w** [comment]
No to rozwiązane udało się zrobić osobny plik przy pomocy @hawkeye116477, komu przeskadza, to niech przeprogramuje swoje edytory hosts:

https://github.com/PolishFiltersTeam/KADhosts/blob/master/KADhosts_without_controversies.txt

https://github.com/PolishFiltersTeam/KADhosts/raw/master/KADhosts_without_controversies.txt

---

Opcjonalnie z tego co widzę to można też te domeny sukcesywnie z realnym IP na własny użytek sobie utrzymywać po regułach KAD - np.:

> `198.185.159.144 jerzyzieba.com`

Niby się ładuje, nawet udało mi się pod `www.wp.pl` załadować `kobieta.wp.pl` (`212.77.100.75`)

**Comment by KonoromiHimaries** [comment]
> sztuczna inteligencja przejęła umysły tworzących tą sekcje, dla tego nie uda się jej usunąć już nigdy.

jak najbardziej rozumiem by dodawać strony "niezaufane" z spisu stron kontrowersyjnych. jednak dodawanie absolutnie wszystkich stron! tylko dla tego że mają powiązania do ruchu alternatywnego, to gruba przesada i aberracja tego czym się tutaj powinniśmy zajmować.

**Comment by KonoromiHimaries** [comment]
na razie jednak trzeba ograniczać skutki, bo to idzie za daleko https://github.com/PolishFiltersTeam/KAD/issues/926

**Comment by KonoromiHimaries** [comment]
https://github.com/PolishFiltersTeam/KAD/issues/926
