### ISSUE TITLE
Lista hosts nie powinna mieć adresów IP zamiast domeny

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/KADhosts#22]
https://github.com/StevenBlack/hosts/issues/1004#issuecomment-503640115

Czyli najlepiej jakby się dało zrobić by takie reguły nie mogły trafić na listę:

https://github.com/PolishFiltersTeam/KADhosts/blob/265f7dd93998e6cab266adef3408ab2b49333762/KADhosts.txt#L2028-L2029

Próbowałem coś kombinując ze składnią uBo, ale nie mam jak wcisnąć gwiazdek, a skrypt sobie tłumaczy filtr nawet po próbie zmiany na:

`|http*://xyz.xyz.xyz.xyz/*$document,~third-party`

**Comment by hawkeye116477** [comment]
@krystian3w Trochę opóźniona prośba, bo ja to już 2 dni temu poprawiłem :stuck_out_tongue:
