### ISSUE TITLE
huit.re is blocked

### ISSUE THREAD

**Issue by clmath** [PolishFiltersTeam/KADhosts#23]
I've noticed that huit.re is blocked.

huit.re is a French URL shortener maintained by [Framasoft](framasoft.org).

Why is it the case? Would it be possible to remove it from the domain list(s)?

Thanks.

**Comment by krystian3w** [comment]
Maybe many fake links to scam?

**Comment by hawkeye116477** [comment]
Maybe, but every url shortener can contain good and bad links...
Anyway, it was also flagged by Eset and Bitdefender as phishing => `https://www.virustotal.com/gui/url/5affb065339928255ec002437d338339379dd0ad25f8556982539c5e9d094870/detection`. 
We'll wait for @azet12 reply.

**Comment by hawkeye116477** [comment]
`Maybe many fake links to scam?`
It can be the case, even they wrote that:
> A lot of spammers use this service to hide malicious URL. We are forced to cut off access to the API, sorry.

As @azet12 said: 
> The site can be added to the list even if it is not directly cheating.
