### ISSUE TITLE
Błędne blokowanie sendgrid.net

### ISSUE THREAD

**Issue by matt08** [PolishFiltersTeam/KADhosts#24]
Filtry blogują domenę sendgrid.net, która jest narzędziem używanym przez wiele sklepów internetowych i firm (także polskich) do wysyłki maili i jako linki w mailach (np. do potwierdzenia konta, pobrania faktury).

https://sendgrid.com/

**Comment by krystian3w** [comment]
Znaczy jak, domena się ładuje?

![obraz](https://user-images.githubusercontent.com/35370833/62826169-0fcccc80-bbb7-11e9-8639-0af94e3d2432.png)

**Comment by krystian3w** [comment]
@KonoromiHimaries  czemu w tabelce jest link na repo `KADhosts`?

**Comment by hawkeye116477** [comment]
Najwyraźniej zostało to dodane, bo było wykorzystywane do przekrętów.
`https://niebezpiecznik.pl/post/ciekawy-phishing-na-klientow-pekao/`
Reguła usunięta już.
