### ISSUE TITLE
spyware.neocities.org

### ISSUE THREAD

**Issue by The-Compiler** [PolishFiltersTeam/KADhosts#26]
https://spyware.neocities.org seems to be blocked under "Promocja pseudonauki / Fake news - Nieprawdziwe, wprowadzajace w blad informacje lub podobne.". Why is that?

**Comment by hawkeye116477** [comment]
Because it's fake news.

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KADhosts/blob/master/KADhosts_without_controversies.txt
