### ISSUE TITLE
invalid entries

### ISSUE THREAD

**Issue by Laicure** [PolishFiltersTeam/KADhosts#28]
latest release as of now got two invalids:
```
www.aconcagua2010.pl$all
aconcagua2010.pl$all
```

**Comment by krystian3w** [comment]
Hi @Laicure,

Do you know if the host files allow for a dot after TLD?

> [http://www.benchmark.pl./](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://www.benchmark.pl./)

**Comment by Laicure** [comment]
> Hi @Laicure,
> 
> Do you know if the host files allow for a dot after TLD?
> 
> > [http://www.benchmark.pl./](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http://www.benchmark.pl./)

hey @krystian3w, it does: https://stackoverflow.com/questions/26574824/is-domain-dot-tld-the-same-as-domain-dot-tld-dot-dot-after-tld
