### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by Laicure** [PolishFiltersTeam/KADhosts#33]
Hi!

I just want to drop it here:

![image](https://user-images.githubusercontent.com/8619566/95736902-6f41d300-0cb9-11eb-9f83-382a826622b7.png)

Thanks!

https://github.com/PolishFiltersTeam/KADhosts/blob/b602e62841a6627175cdd9c4cc6b8bc4f501d528/KADhosts.txt#L11652 https://github.com/PolishFiltersTeam/KADhosts/blob/b602e62841a6627175cdd9c4cc6b8bc4f501d528/KADhosts.txt#L13169

**Comment by hawkeye116477** [comment]
@krystian3w https://github.com/PolishFiltersTeam/KADhosts/commit/f12a30f2a9909c1de1f6a0b85031d7046db68f36

**Comment by Laicure** [comment]
Apologies, here are the exact ones:
[Line 13129 from KADhosts](https://github.com/PolishFiltersTeam/KADhosts/blob/master/KADhosts.txt#L13129)
[Line 11642 from KADhosts](https://github.com/PolishFiltersTeam/KADhosts/blob/master/KADhosts.txt#L11642)

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/KADhosts/commit/f12a30f2a9909c1de1f6a0b85031d7046db68f36 - scam pages, KAD for uBO use wildcard, so moved to `hostplus.txt`.

I copied with `gremlins`?

--
https://github.com/PolishFiltersTeam/KADhosts/blob/master/KADhosts.txt#L13129 + https://github.com/PolishFiltersTeam/KADhosts/blob/master/KADhosts.txt#L11642 = looks normal, that are very old blocked domains.

**Comment by Laicure** [comment]
Thanks, please close when necessary.

**Comment by krystian3w** [comment]
Try force update after 10 minutes, when so possible download version with:

 `0.0.0.0 domain-riddexpl1.com `
 `0.0.0.0 www.domain-riddexpl1.com `
