### ISSUE TITLE
FR: add filter lists without 0.0.0.0 at the beginning

### ISSUE THREAD

**Issue by suprovsky** [PolishFiltersTeam/KADhosts#34]
Hey, I believe you're doing a great job with maintaining that list, however I wanted to use your list on FortiGate and I can't since it reads domains only, so it's impossible to use your lists here since it starts with an IP address 0.0.0.0 which is fine for PiHole because it directs these domain to this address which is not a case here. I am not sure about this but I think other UTM-grade devices would support such domain name thread feed like this. Would you mind just maintaining a second file with domain names only? This would be very helpful.

This is an example how do I use a different domain name threat feed from firebog:
https://i.imgur.com/ThjEbZy.png

**Comment by hawkeye116477** [comment]
You can test new list from https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADomains.txt.

**Comment by suprovsky** [comment]
![image](https://user-images.githubusercontent.com/13705604/97918040-b9b4ed80-1d55-11eb-93b8-b71c07cf8265.png)
Thanks a lot, works!
