### ISSUE TITLE
amway.com is blocked

### ISSUE THREAD

**Issue by crssi** [PolishFiltersTeam/KADhosts#35]
Would you, please, remove amway.com from the list.

Thank you in advance and cheers

**Comment by hawkeye116477** [comment]
@krystian3w 

https://github.com/PolishFiltersTeam/KAD/issues/744

```
https://finanse.wp.pl/amerykanski-sen-polska-rzeczywistosc-6114569809672321a
https://magnifier.pl/piramida-finansowa-mlm/
https://artelis.pl/artykuly/26660/opinia-o-amway-to-prawdziwa-firma-czy-piramida-finansowa
```

**Comment by krystian3w** [comment]
removed:

https://github.com/PolishFiltersTeam/KADhosts/commit/77cd318a40b3c1747314e1c4577ad2cac451adea
https://github.com/PolishFiltersTeam/KADhosts/commit/4d924f13c87c803941bc7c7e0a192407264dff1f
https://github.com/PolishFiltersTeam/KADhosts/commit/ae42191c6dfbc5dfa7c47c9c78fa4f5d41b7e815
