### ISSUE TITLE
KADhole - jak importować?

### ISSUE THREAD

**Issue by rAmfu** [PolishFiltersTeam/KADhosts#38]
Wklejam kod błędu aby można było go naprawić.

[i] Target: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhole.txt
  [✓] Status: Retrieval successful
  [i] Received 35 domains, 35 domains invalid!
      Sample of invalid domains:

```
      - (^|\.)komornik.*-gov\.tk$
      - (^|\.)pulsoksymetr.*-pl\.com$
      - (^|\.)xn.*gwatpolska24*\.*$
      - (^|\.).*automatyczny-dozownikmydla-pl\.com$
      - (^|\.).*automatyczny-dozownik-mydla-pl\.com$
```

**Comment by krystian3w** [comment]
W demie błędnych filtrów może nagle zapis `.*` stał się przestarzały.

**Comment by hawkeye116477** [comment]
A w jaki sposób to zostało dodane? Bo zwykle taki komunikat raczej podaje, jak wklejasz link w panel admina. W taki sposób nie dodaje się listy regex.

**Comment by rAmfu** [comment]
No właśnie, przez panel. Dziś dodam przez terminal.

**Comment by rAmfu** [comment]
Problem dalej występuje pomimo dodanie przez terminal.

**Comment by krystian3w** [comment]
Jak stary np. python masz na malinie?

Zalecany jest 3.6 i nowszy.

**Comment by hawkeye116477** [comment]
Jaki dokladnie jest komunikat błędu i czy usunąłeś adres z panelu?

**Comment by rAmfu** [comment]
Po najnowszej aktualizacji wszystko śmiga jak należy. Widocznie był błąd który dokładnie nie byłem w stanie sam znaleźć.
Dziękuję i przepraszam wszystkich za zamieszanie.
Piona 🤚
