### ISSUE TITLE
Please remove ipsnews.net from blocklist or only block the /business sub-site

### ISSUE THREAD

**Issue by anupshah** [PolishFiltersTeam/KADhosts#42]
Hello,

This is a follow up from my issue originally reported here:

https://github.com/nextdns/metadata/issues/626

That then led me to https://github.com/StevenBlack/hosts/issues/1592 who suggested I report it here.

At the same time, in the first link, @krystian3w was kind enough to point out the offending article that caused the site to be blocked:

> Hacked or have accepted a bribe:
> 
> ipsnews.net/business/2021/03/18/bitcoin-era-opinie-czy-bot-to-oszustwo-2021/
>
> https://web.archive.org/web/20210320095109/ipsnews.net/business/2021/03/18/bitcoin-era-opinie-czy-bot-to-oszustwo-2021/

ipsnews.net is a legit news site, and I have consumed their news for 20+ years, while also integrating their news feed for the past 10+ years. In all that time, I admittedly have not come across ipsnews.net/business as it doesn't appear to be linked from the main site. Indeed, it doesn't seem as related to the rest of the style of news that Inter Press Service does, so not sure what is going on there.

I wonder what is happening there.

Would it be possible to block either just that story or ipsnews.net/business but not the entire domain?

I will reach out to ipsnews.net to try and figure out what is going on.

Thanks!

**Comment by krystian3w** [comment]
Deleted: https://github.com/PolishFiltersTeam/KADhosts/commit/761e8e916adde3b6c0285ef525d0f57b8cd712a1#diff-0cb6b2b322378cb88a5ef38147d3fea603a48615f505e9cae7d5eaf18bf6a603L6353

**Comment by krystian3w** [comment]
On DNS level no possible block catalog "`/business`" or URL path for article.

**Comment by anupshah** [comment]
Thanks.

And yes, of course, on DNS level can't block sub-path, silly me... Not sure what I was thinking...! 🤦 

I will still reach out to that site to find out what is going on there. Many thanks.

**Comment by anupshah** [comment]
@krystian3w as FYI, I got a response from them; they were trying some new avenues because, as many media outlets are finding, they are facing tough times, which is a shame, as IPS is awesome... I guess they just partnered with an entity for some content that was not up to their usual standards....
