### ISSUE TITLE
Invalid Domains

### ISSUE THREAD

**Issue by GenusGeoff** [PolishFiltersTeam/KADhosts#46]
[i] Analyzed 32750 domains, 2 domains invalid!
      Sample of invalid domains:
      - b=time.pw
      - www.b=time.pw

**Comment by krystian3w** [comment]
Wait 10 minutes and try force udpate list from `raw.github.com` domain.

DNS serivces most based on to rare updated https://github.com/StevenBlack/hosts#sources-of-hosts-data-unified-in-this-variant

> frequently
